#!/bin/sh 

auto_page() {
	PAGEVIEW_FILE="$(mktemp --tmpdir ".out.XXXXXXXX")"
	# Early exit cleanup
	trap "rm -f '${PAGEVIEW_FILE}'; unset -v PAGEVIEW_FILE" EXIT TERM HUP INT
	if [ "${#}" -gt 0 ]; then
		script --quiet -c "${*}" >> "${PAGEVIEW_FILE}"
	elif [ ! -t 0 ]; then
		cat >> "${PAGEVIEW_FILE}"
		# If the file is empty don't bother paging
		[ ! -s "${PAGEVIEW_FILE}" ] && return 0
	else
		echo "Usage: ${0} <command> [args...]"
		return 1
	fi

	${PAGER-less -r} "${PAGEVIEW_FILE}"
	\cat "${PAGEVIEW_FILE}"
	rm -f "${PAGEVIEW_FILE}"
	unset -v PAGEVIEW_FILE
}

auto_page "${@}"
