#!/bin/bash

check_truecolor() {
    local response

    local old_stty
    old_stty="$(stty -g)"

    stty raw -echo

    printf '\x1B]4;2;?\x1B\\'
    read -t 0.5 -s -r -d '\' response
    stty "${old_stty}"

    if [[ "${response}" == *';rgb:'* ]]; then
        return 0;
    fi
    return 1;
}

[[ "${-}" == *i* ]] || check_truecolor "${@}"
