#!/usr/bin/bash

check_truecolor() {
    local response

    local old_stty
    old_stty="$(stty -g)"

    stty raw -echo

    printf '\e]4;2;?\e\\'
    read -t 0.5 -s -r -d '\' response
    stty "${old_stty}"

    if [[ "${response}" == *';rgb:'* ]]; then
        return 0;
    fi
    return 1;
}

check_truecolor "${@}"
