#!/bin/bash
newterm() {
    local session_window_class
    local wayland_address
    local selected_tmux_session
    session_window_class='tmux-iterm'

    trap "unset -f find_tmux_session add_tmux_pane get_focused_workspace_name" RETURN
    # 1 = priority workspace
    # 2 = all other workspaces to search
    find_tmux_session() {
        local pid
        # check all workspaces starting with the priority workspace
        for ws in "${@}"; do
            read -r wayland_address pid <<< "$(hyprctl clients -j | jq -r ".[] | select(.workspace.id == (${ws} | tonumber) and .class == \"${session_window_class}\") | \"\\(.address) \\(.pid)\"")"
            if [ -n "${wayland_address}" ]; then
                local tmux_client_pid
                tmux_client_pid="$(ps --ppid "${pid}" -o pid= | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')"
                selected_tmux_session="$(tmux list-client -F "#{client_session}" -f "#{==:#{client_pid},${tmux_client_pid}}")"
                return 0
            fi
        done
        
        return 1
    }
    add_tmux_pane() {
        # Gets the currently active window in the existing session
        local active_window
        active_window="$(tmux list-windows -F '#{?window_active,#{window_index},}' -t "${1}")"
        tmux split-window -h -t "${1}:${active_window}" ${2:+--} ${2}
    }
    get_focused_workspace_name() {
        hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .activeWorkspace.name'
    }
    local focused_workspace
    local visible_workspaces
    local wayland_address
    local command
    command="${*}"
    focused_workspace=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .activeWorkspace.id')
    visible_workspaces=$(hyprctl monitors -j | jq -r '.[] | select(.focused == false) | .activeWorkspace.id')
    
    find_tmux_session "${focused_workspace}" "${visible_workspaces}"
    
    if [ -z "${wayland_address}" ]; then
        local workspace_name
        workspace_name="hypr_$(get_focused_workspace_name)"
        
        local hyprland_command
        
        hyprland_command="${NEWTERM_WINDOW_CMD:-"${HOME}/local/bin/run_app.sh foot --app-id='${session_window_class}'"} tmux new -AD -s '${workspace_name}'"

        echo "${hyprland_command}"

        [ -n "${command}" ] && hyprland_command="${hyprland_command} '${command}'"

        # Create new window if no window found
        hyprctl dispatch execr "${hyprland_command} > /tmp/log 2>&1"
    else
        # Gotta get the workspace of the focused tmux window
        add_tmux_pane "${selected_tmux_session}" "${command}"
        hyprctl dispatch focuswindow "address:${wayland_address}" > /dev/null
    fi
}

[[ "${-}" == *i* ]] || newterm "${@}"
